In [1]:
import numpy as np

In [2]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.sqrt(arr)

array([[ 0.        ,  1.        ,  1.41421356],
       [ 1.73205081,  2.        ,  2.23606798],
       [ 2.44948974,  2.64575131,  2.82842712]])

In [4]:
np.exp(arr)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

In [6]:
np.log(arr+1)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947],
       [ 1.94591015,  2.07944154,  2.19722458]])

** Create a random normal distributed array

In [13]:
A = np.random.randn(10)
A

array([-0.42311479,  1.45246575,  3.40995932, -2.27487494, -0.34845519,
        0.9200316 ,  1.04148859, -0.26937992, -0.33996004,  0.8873767 ])

In [15]:
B = np.random.randn(10)
B

array([-0.52676987,  0.26601951,  0.33176331,  0.15703868, -0.43233489,
       -0.25249678, -0.11725571,  1.36960994,  0.3376107 , -1.28101043])

In [12]:
np.random.randn(9).reshape((3,3))

array([[-0.12645261,  0.59646278,  1.09612765],
       [-0.26830946,  0.28880529, -0.00662109],
       [-0.26442764,  0.5271515 ,  1.7165204 ]])

Binary functions

In [17]:
np.add(A,B)

array([ -9.49884656e-01,   1.71848526e+00,   3.74172263e+00,
        -2.11783627e+00,  -7.80790083e-01,   6.67534822e-01,
         9.24232877e-01,   1.10023002e+00,  -2.34934299e-03,
        -3.93633734e-01])

In [20]:
np.maximum(A,B)

array([-0.42311479,  1.45246575,  3.40995932,  0.15703868, -0.34845519,
        0.9200316 ,  1.04148859,  1.36960994,  0.3376107 ,  0.8873767 ])

In [21]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [23]:
np.bitwise_and(np.array([1,2,0,0,1]), np.array([1,0,0,1,3]))

array([1, 0, 0, 0, 1], dtype=int32)