In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


In [5]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([arr1,arr1], axis =1)



array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
np.concatenate([arr1,arr1], axis =0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
ser1 = Series([1,2,3],index = ['A','B','C'])
ser1

A    1
B    2
C    3
dtype: int64

In [13]:
ser2 = Series([4,5],index = ['D','E'])
ser2


D    4
E    5
dtype: int64

In [14]:
pd.concat([ser1,ser2])

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [15]:
pd.concat([ser1,ser2],axis = 1)

0   1
A   1 NaN
B   2 NaN
C   3 NaN
D NaN   4
E NaN   5

In [16]:
pd.concat([ser1,ser2],axis = 0)

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [17]:
pd.concat([ser1,ser2], keys = ['key1','key2'])

key1  A    1
      B    2
      C    3
key2  D    4
      E    5
dtype: int64

In [21]:
df1 = DataFrame(np.random.randn(4,3),columns = ['X','Y','Z'])
df1

X         Y         Z
0 -0.517815  0.739118  0.308126
1  1.048359  0.185633  0.398086
2 -1.361591 -1.171546 -0.813177
3 -1.744741  0.950266  0.662776

In [22]:
df2 = DataFrame(np.random.randn(3,3),columns = ['Y','Q','X'])
df2

Y         Q         X
0  0.395346 -0.380608 -0.845167
1  0.300459  0.481986 -1.093754
2 -0.787442  0.847730  0.334654

In [24]:
pd.concat([df1,df2])

Q         X         Y         Z
0       NaN -0.517815  0.739118  0.308126
1       NaN  1.048359  0.185633  0.398086
2       NaN -1.361591 -1.171546 -0.813177
3       NaN -1.744741  0.950266  0.662776
0 -0.380608 -0.845167  0.395346       NaN
1  0.481986 -1.093754  0.300459       NaN
2  0.847730  0.334654 -0.787442       NaN

In [25]:
pd.concat([df1,df2], ignore_index = True)

Q         X         Y         Z
0       NaN -0.517815  0.739118  0.308126
1       NaN  1.048359  0.185633  0.398086
2       NaN -1.361591 -1.171546 -0.813177
3       NaN -1.744741  0.950266  0.662776
4 -0.380608 -0.845167  0.395346       NaN
5  0.481986 -1.093754  0.300459       NaN
6  0.847730  0.334654 -0.787442       NaN

In [26]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'