In [1]:
import numpy as np

# Indexing in 1d array

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
arr[3]

3

In [15]:
arr[2:5]

array([2, 3, 4])

In [16]:
arr[3:5] = [1,1]

In [17]:
arr

array([ 0,  1,  2,  1,  1,  5,  6,  7,  8,  9, 10])

In [19]:
arr[3:6] = 100

In [20]:
arr

array([  0,   1,   2, 100, 100, 100,   6,   7,   8,   9,  10])

In [23]:
arr[3:6] = np.zeros(3)

In [24]:
arr

array([ 0,  1,  2,  0,  0,  0,  6,  7,  8,  9, 10])

In [26]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[-1]

10

In [32]:
arr[-5:-1]

array([6, 7, 8, 9])

In [34]:
arr[-10:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[-2:111]

array([ 9, 10])

In [38]:
arr[12]

IndexError: index 12 is out of bounds for axis 0 with size 11

In [40]:
slice_arr = arr[0:5]
slice_arr

array([0, 1, 2, 3, 4])

In [41]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

Assignment creates only a sallow copy. the slice_arr here will be just a view of the original array

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

user array.copy() method if you want a deep copy of the array

In [46]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
arr2 = arr.copy()

In [48]:
arr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [49]:
arr2[:] = 5

In [50]:
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [53]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Indexing in 2d array

In [56]:
[[1,2,3]]*5 #example for normal lists multiplication

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [57]:
arr2d = np.array([[1,2,3],[11,12,15],[20,25,30]])

In [58]:
arr2d

array([[ 1,  2,  3],
       [11, 12, 15],
       [20, 25, 30]])

In [59]:
arr2d[1]

array([11, 12, 15])

In [60]:
arr2d[0:2]

array([[ 1,  2,  3],
       [11, 12, 15]])

In [65]:
arr2d[1][2]

15

In [67]:
arr2d[0:2,1:3]

array([[ 2,  3],
       [12, 15]])

In [68]:
arr2d[1,2]

15

In [88]:
arr_2d= np.zeros((10,10))

In [89]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [90]:
arr_2d.shape

(10, 10)

In [91]:
arr_len = arr_2d.shape[0]
arr_len

10

# Fancy Indexing

In [92]:
for i in range(arr_len):
    arr_2d[i] = i

In [93]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [98]:
arr_2d[[1,3,7]]


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [99]:
arr_2d[[6,1,3]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]])

In [102]:
arr_2d[[6,1,3],1]

array([ 6.,  1.,  3.])

In [103]:
arr_2d[[6,1,3],[1,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 