In [15]:
import numpy as np

# Division examples

In [10]:
1/3


0.3333333333333333

In [11]:
1//3

0

In [12]:
5//2

2

In [13]:
5.5//2

2.0

In [14]:
5.5/2

2.75

# Array and scalar operations

In [16]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [19]:
arr1*5


array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [22]:
arr1**3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [23]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [25]:
arr1+arr1


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])