In [1]:
import numpy as np

In [2]:
arr =np.arange(50).reshape((10,5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [16]:
tarr = arr[:,1]
tarr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [18]:
tarr.shape

(10,)

In [19]:
tarr = arr.T

In [20]:
tarr

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

Even Tanspose is not a deep copy.

In [21]:
tarr[0,0] =100
tarr

array([[100,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  1,   6,  11,  16,  21,  26,  31,  36,  41,  46],
       [  2,   7,  12,  17,  22,  27,  32,  37,  42,  47],
       [  3,   8,  13,  18,  23,  28,  33,  38,  43,  48],
       [  4,   9,  14,  19,  24,  29,  34,  39,  44,  49]])

In [22]:
arr

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [25]:
arr1 = np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
arr2 = np.arange(6,12).reshape(3,2)
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
arr_dot = arr1.dot(arr2)
arr_dot

array([[ 28,  31],
       [100, 112]])

In [31]:
arr3d = np.arange(48).reshape((3,4,4))
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [33]:
arr3d[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
arr3d[0][1]

array([4, 5, 6, 7])

In [35]:
arr3d.T

array([[[ 0, 16, 32],
        [ 4, 20, 36],
        [ 8, 24, 40],
        [12, 28, 44]],

       [[ 1, 17, 33],
        [ 5, 21, 37],
        [ 9, 25, 41],
        [13, 29, 45]],

       [[ 2, 18, 34],
        [ 6, 22, 38],
        [10, 26, 42],
        [14, 30, 46]],

       [[ 3, 19, 35],
        [ 7, 23, 39],
        [11, 27, 43],
        [15, 31, 47]]])

In [36]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [37]:
arr3d.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [16, 17, 18, 19],
        [32, 33, 34, 35]],

       [[ 4,  5,  6,  7],
        [20, 21, 22, 23],
        [36, 37, 38, 39]],

       [[ 8,  9, 10, 11],
        [24, 25, 26, 27],
        [40, 41, 42, 43]],

       [[12, 13, 14, 15],
        [28, 29, 30, 31],
        [44, 45, 46, 47]]])

In [44]:
arr = np.array([[1,2,3]])

In [45]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])