In [1]:
"""Softmax."""

scores = [3.0, 1.0, 0.2]
import numpy as np

In [2]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x)/np.sum(np.exp(x),axis=0)





In [3]:
print(softmax(scores))

[ 0.8360188   0.11314284  0.05083836]


In [4]:
# Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])



In [5]:
scores.shape,x.shape,scores.shape[1]

((3, 80), (80,), 80)

In [6]:
plt.plot(x, softmax(scores).T, linewidth=2)
plt.show()


In [17]:
np.exp(scores).shape

(3, 80)

In [19]:
np.sum(np.exp(scores),axis=0).shape

(80,)

In [21]:
t=np.exp(scores)/np.sum(np.exp(scores),axis=0)
t.shape

(3, 80)

In [23]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])

In [24]:

a

array([1, 2, 3])

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a/b

array([[ 1.  ,  1.  ,  1.  ],
       [ 0.25,  0.4 ,  0.5 ]])